//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace ClientWindowsFormsApplication1.Rozgrywki {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RozgrywkiSoap", Namespace="http://tempuri.org/")]
    public partial class Rozgrywki : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listaUzytkownikowOperationCompleted;
        
        private System.Threading.SendOrPostCallback KtoWygralOperationCompleted;
        
        private System.Threading.SendOrPostCallback naStoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback genOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzPokojeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DolaczDoStoluOperationCompleted;
        
        private System.Threading.SendOrPostCallback OpuscStolOperationCompleted;
        
        private System.Threading.SendOrPostCallback UtworzStolOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzStanStoluOperationCompleted;
        
        private System.Threading.SendOrPostCallback WyslijRuchOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Rozgrywki() {
            this.Url = global::ClientWindowsFormsApplication1.Properties.Settings.Default.ClientWindowsFormsApplication1_Rozgrywki_Rozgrywki;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listaUzytkownikowCompletedEventHandler listaUzytkownikowCompleted;
        
        /// <remarks/>
        public event KtoWygralCompletedEventHandler KtoWygralCompleted;
        
        /// <remarks/>
        public event naStoleCompletedEventHandler naStoleCompleted;
        
        /// <remarks/>
        public event genCompletedEventHandler genCompleted;
        
        /// <remarks/>
        public event PobierzPokojeCompletedEventHandler PobierzPokojeCompleted;
        
        /// <remarks/>
        public event DolaczDoStoluCompletedEventHandler DolaczDoStoluCompleted;
        
        /// <remarks/>
        public event OpuscStolCompletedEventHandler OpuscStolCompleted;
        
        /// <remarks/>
        public event UtworzStolCompletedEventHandler UtworzStolCompleted;
        
        /// <remarks/>
        public event PobierzStanStoluCompletedEventHandler PobierzStanStoluCompleted;
        
        /// <remarks/>
        public event WyslijRuchCompletedEventHandler WyslijRuchCompleted;
        
        /// <remarks/>
        public event StartCompletedEventHandler StartCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaUzytkownikow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Uzytkownik[] listaUzytkownikow(long numer) {
            object[] results = this.Invoke("listaUzytkownikow", new object[] {
                        numer});
            return ((Uzytkownik[])(results[0]));
        }
        
        /// <remarks/>
        public void listaUzytkownikowAsync(long numer) {
            this.listaUzytkownikowAsync(numer, null);
        }
        
        /// <remarks/>
        public void listaUzytkownikowAsync(long numer, object userState) {
            if ((this.listaUzytkownikowOperationCompleted == null)) {
                this.listaUzytkownikowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaUzytkownikowOperationCompleted);
            }
            this.InvokeAsync("listaUzytkownikow", new object[] {
                        numer}, this.listaUzytkownikowOperationCompleted, userState);
        }
        
        private void OnlistaUzytkownikowOperationCompleted(object arg) {
            if ((this.listaUzytkownikowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaUzytkownikowCompleted(this, new listaUzytkownikowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KtoWygral", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Uzytkownik[] KtoWygral(long numer) {
            object[] results = this.Invoke("KtoWygral", new object[] {
                        numer});
            return ((Uzytkownik[])(results[0]));
        }
        
        /// <remarks/>
        public void KtoWygralAsync(long numer) {
            this.KtoWygralAsync(numer, null);
        }
        
        /// <remarks/>
        public void KtoWygralAsync(long numer, object userState) {
            if ((this.KtoWygralOperationCompleted == null)) {
                this.KtoWygralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKtoWygralOperationCompleted);
            }
            this.InvokeAsync("KtoWygral", new object[] {
                        numer}, this.KtoWygralOperationCompleted, userState);
        }
        
        private void OnKtoWygralOperationCompleted(object arg) {
            if ((this.KtoWygralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KtoWygralCompleted(this, new KtoWygralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/naStole", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Karta[] naStole(long numer) {
            object[] results = this.Invoke("naStole", new object[] {
                        numer});
            return ((Karta[])(results[0]));
        }
        
        /// <remarks/>
        public void naStoleAsync(long numer) {
            this.naStoleAsync(numer, null);
        }
        
        /// <remarks/>
        public void naStoleAsync(long numer, object userState) {
            if ((this.naStoleOperationCompleted == null)) {
                this.naStoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnaStoleOperationCompleted);
            }
            this.InvokeAsync("naStole", new object[] {
                        numer}, this.naStoleOperationCompleted, userState);
        }
        
        private void OnnaStoleOperationCompleted(object arg) {
            if ((this.naStoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.naStoleCompleted(this, new naStoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/gen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string gen(long numer) {
            object[] results = this.Invoke("gen", new object[] {
                        numer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void genAsync(long numer) {
            this.genAsync(numer, null);
        }
        
        /// <remarks/>
        public void genAsync(long numer, object userState) {
            if ((this.genOperationCompleted == null)) {
                this.genOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenOperationCompleted);
            }
            this.InvokeAsync("gen", new object[] {
                        numer}, this.genOperationCompleted, userState);
        }
        
        private void OngenOperationCompleted(object arg) {
            if ((this.genCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.genCompleted(this, new genCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzPokoje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pokoj[] PobierzPokoje(string token) {
            object[] results = this.Invoke("PobierzPokoje", new object[] {
                        token});
            return ((Pokoj[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzPokojeAsync(string token) {
            this.PobierzPokojeAsync(token, null);
        }
        
        /// <remarks/>
        public void PobierzPokojeAsync(string token, object userState) {
            if ((this.PobierzPokojeOperationCompleted == null)) {
                this.PobierzPokojeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzPokojeOperationCompleted);
            }
            this.InvokeAsync("PobierzPokoje", new object[] {
                        token}, this.PobierzPokojeOperationCompleted, userState);
        }
        
        private void OnPobierzPokojeOperationCompleted(object arg) {
            if ((this.PobierzPokojeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzPokojeCompleted(this, new PobierzPokojeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DolaczDoStolu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat DolaczDoStolu(string token, long numer) {
            object[] results = this.Invoke("DolaczDoStolu", new object[] {
                        token,
                        numer});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void DolaczDoStoluAsync(string token, long numer) {
            this.DolaczDoStoluAsync(token, numer, null);
        }
        
        /// <remarks/>
        public void DolaczDoStoluAsync(string token, long numer, object userState) {
            if ((this.DolaczDoStoluOperationCompleted == null)) {
                this.DolaczDoStoluOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDolaczDoStoluOperationCompleted);
            }
            this.InvokeAsync("DolaczDoStolu", new object[] {
                        token,
                        numer}, this.DolaczDoStoluOperationCompleted, userState);
        }
        
        private void OnDolaczDoStoluOperationCompleted(object arg) {
            if ((this.DolaczDoStoluCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DolaczDoStoluCompleted(this, new DolaczDoStoluCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OpuscStol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat OpuscStol(string token, long numer) {
            object[] results = this.Invoke("OpuscStol", new object[] {
                        token,
                        numer});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void OpuscStolAsync(string token, long numer) {
            this.OpuscStolAsync(token, numer, null);
        }
        
        /// <remarks/>
        public void OpuscStolAsync(string token, long numer, object userState) {
            if ((this.OpuscStolOperationCompleted == null)) {
                this.OpuscStolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpuscStolOperationCompleted);
            }
            this.InvokeAsync("OpuscStol", new object[] {
                        token,
                        numer}, this.OpuscStolOperationCompleted, userState);
        }
        
        private void OnOpuscStolOperationCompleted(object arg) {
            if ((this.OpuscStolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpuscStolCompleted(this, new OpuscStolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UtworzStol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat UtworzStol(string token, string nazwa, int maxGraczy, long stawkaWe, long bigBlind) {
            object[] results = this.Invoke("UtworzStol", new object[] {
                        token,
                        nazwa,
                        maxGraczy,
                        stawkaWe,
                        bigBlind});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void UtworzStolAsync(string token, string nazwa, int maxGraczy, long stawkaWe, long bigBlind) {
            this.UtworzStolAsync(token, nazwa, maxGraczy, stawkaWe, bigBlind, null);
        }
        
        /// <remarks/>
        public void UtworzStolAsync(string token, string nazwa, int maxGraczy, long stawkaWe, long bigBlind, object userState) {
            if ((this.UtworzStolOperationCompleted == null)) {
                this.UtworzStolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUtworzStolOperationCompleted);
            }
            this.InvokeAsync("UtworzStol", new object[] {
                        token,
                        nazwa,
                        maxGraczy,
                        stawkaWe,
                        bigBlind}, this.UtworzStolOperationCompleted, userState);
        }
        
        private void OnUtworzStolOperationCompleted(object arg) {
            if ((this.UtworzStolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UtworzStolCompleted(this, new UtworzStolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzStanStolu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Akcja[] PobierzStanStolu(string token) {
            object[] results = this.Invoke("PobierzStanStolu", new object[] {
                        token});
            return ((Akcja[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzStanStoluAsync(string token) {
            this.PobierzStanStoluAsync(token, null);
        }
        
        /// <remarks/>
        public void PobierzStanStoluAsync(string token, object userState) {
            if ((this.PobierzStanStoluOperationCompleted == null)) {
                this.PobierzStanStoluOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzStanStoluOperationCompleted);
            }
            this.InvokeAsync("PobierzStanStolu", new object[] {
                        token}, this.PobierzStanStoluOperationCompleted, userState);
        }
        
        private void OnPobierzStanStoluOperationCompleted(object arg) {
            if ((this.PobierzStanStoluCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzStanStoluCompleted(this, new PobierzStanStoluCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WyslijRuch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat WyslijRuch(string token, Akcja akcja, long numer) {
            object[] results = this.Invoke("WyslijRuch", new object[] {
                        token,
                        akcja,
                        numer});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void WyslijRuchAsync(string token, Akcja akcja, long numer) {
            this.WyslijRuchAsync(token, akcja, numer, null);
        }
        
        /// <remarks/>
        public void WyslijRuchAsync(string token, Akcja akcja, long numer, object userState) {
            if ((this.WyslijRuchOperationCompleted == null)) {
                this.WyslijRuchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWyslijRuchOperationCompleted);
            }
            this.InvokeAsync("WyslijRuch", new object[] {
                        token,
                        akcja,
                        numer}, this.WyslijRuchOperationCompleted, userState);
        }
        
        private void OnWyslijRuchOperationCompleted(object arg) {
            if ((this.WyslijRuchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WyslijRuchCompleted(this, new WyslijRuchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Start", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat Start(string token, long numer) {
            object[] results = this.Invoke("Start", new object[] {
                        token,
                        numer});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void StartAsync(string token, long numer) {
            this.StartAsync(token, numer, null);
        }
        
        /// <remarks/>
        public void StartAsync(string token, long numer, object userState) {
            if ((this.StartOperationCompleted == null)) {
                this.StartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartOperationCompleted);
            }
            this.InvokeAsync("Start", new object[] {
                        token,
                        numer}, this.StartOperationCompleted, userState);
        }
        
        private void OnStartOperationCompleted(object arg) {
            if ((this.StartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartCompleted(this, new StartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Uzytkownik {
        
        private long identyfikatorUzytkownikaField;
        
        private string nazwaUzytkownikaField;
        
        private long numerPokojuField;
        
        private Karta[] handField;
        
        private Karta[] najUkladField;
        
        private int kickerField;
        
        private bool foldField;
        
        private int wartField;
        
        private string nazwaUkladuField;
        
        private bool startField;
        
        /// <remarks/>
        public long identyfikatorUzytkownika {
            get {
                return this.identyfikatorUzytkownikaField;
            }
            set {
                this.identyfikatorUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public string nazwaUzytkownika {
            get {
                return this.nazwaUzytkownikaField;
            }
            set {
                this.nazwaUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                this.numerPokojuField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] hand {
            get {
                return this.handField;
            }
            set {
                this.handField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] najUklad {
            get {
                return this.najUkladField;
            }
            set {
                this.najUkladField = value;
            }
        }
        
        /// <remarks/>
        public int kicker {
            get {
                return this.kickerField;
            }
            set {
                this.kickerField = value;
            }
        }
        
        /// <remarks/>
        public bool fold {
            get {
                return this.foldField;
            }
            set {
                this.foldField = value;
            }
        }
        
        /// <remarks/>
        public int wart {
            get {
                return this.wartField;
            }
            set {
                this.wartField = value;
            }
        }
        
        /// <remarks/>
        public string nazwaUkladu {
            get {
                return this.nazwaUkladuField;
            }
            set {
                this.nazwaUkladuField = value;
            }
        }
        
        /// <remarks/>
        public bool start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Karta {
        
        private figuraKarty figuraField;
        
        private kolorKarty kolorField;
        
        /// <remarks/>
        public figuraKarty figura {
            get {
                return this.figuraField;
            }
            set {
                this.figuraField = value;
            }
        }
        
        /// <remarks/>
        public kolorKarty kolor {
            get {
                return this.kolorField;
            }
            set {
                this.kolorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum figuraKarty {
        
        /// <remarks/>
        K2,
        
        /// <remarks/>
        K3,
        
        /// <remarks/>
        K4,
        
        /// <remarks/>
        K5,
        
        /// <remarks/>
        K6,
        
        /// <remarks/>
        K7,
        
        /// <remarks/>
        K8,
        
        /// <remarks/>
        K9,
        
        /// <remarks/>
        K10,
        
        /// <remarks/>
        KJ,
        
        /// <remarks/>
        KD,
        
        /// <remarks/>
        KK,
        
        /// <remarks/>
        KA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum kolorKarty {
        
        /// <remarks/>
        pik,
        
        /// <remarks/>
        kier,
        
        /// <remarks/>
        karo,
        
        /// <remarks/>
        trefl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Akcja {
        
        private long identyfikatorGraczaField;
        
        private string nazwaAkcjiField;
        
        private int stempelCzasowyField;
        
        private long numerStoluField;
        
        private Karta[] kartyGraczaField;
        
        private Karta[] kartyNaStoleField;
        
        private bool malyBlindField;
        
        private bool duzyBlindField;
        
        private long obecnaStawkaStoluField;
        
        private long obecnaStawkaGraczaField;
        
        private long iloscKasyNaStoleField;
        
        private long iloscKasyGraczaField;
        
        private long nastepnyGraczField;
        
        /// <remarks/>
        public long identyfikatorGracza {
            get {
                return this.identyfikatorGraczaField;
            }
            set {
                this.identyfikatorGraczaField = value;
            }
        }
        
        /// <remarks/>
        public string nazwaAkcji {
            get {
                return this.nazwaAkcjiField;
            }
            set {
                this.nazwaAkcjiField = value;
            }
        }
        
        /// <remarks/>
        public int stempelCzasowy {
            get {
                return this.stempelCzasowyField;
            }
            set {
                this.stempelCzasowyField = value;
            }
        }
        
        /// <remarks/>
        public long numerStolu {
            get {
                return this.numerStoluField;
            }
            set {
                this.numerStoluField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] kartyGracza {
            get {
                return this.kartyGraczaField;
            }
            set {
                this.kartyGraczaField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] kartyNaStole {
            get {
                return this.kartyNaStoleField;
            }
            set {
                this.kartyNaStoleField = value;
            }
        }
        
        /// <remarks/>
        public bool malyBlind {
            get {
                return this.malyBlindField;
            }
            set {
                this.malyBlindField = value;
            }
        }
        
        /// <remarks/>
        public bool duzyBlind {
            get {
                return this.duzyBlindField;
            }
            set {
                this.duzyBlindField = value;
            }
        }
        
        /// <remarks/>
        public long obecnaStawkaStolu {
            get {
                return this.obecnaStawkaStoluField;
            }
            set {
                this.obecnaStawkaStoluField = value;
            }
        }
        
        /// <remarks/>
        public long obecnaStawkaGracza {
            get {
                return this.obecnaStawkaGraczaField;
            }
            set {
                this.obecnaStawkaGraczaField = value;
            }
        }
        
        /// <remarks/>
        public long iloscKasyNaStole {
            get {
                return this.iloscKasyNaStoleField;
            }
            set {
                this.iloscKasyNaStoleField = value;
            }
        }
        
        /// <remarks/>
        public long iloscKasyGracza {
            get {
                return this.iloscKasyGraczaField;
            }
            set {
                this.iloscKasyGraczaField = value;
            }
        }
        
        /// <remarks/>
        public long nastepnyGracz {
            get {
                return this.nastepnyGraczField;
            }
            set {
                this.nastepnyGraczField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Komunikat {
        
        private string trescKomunikatuField;
        
        private long kodKomunikatuField;
        
        /// <remarks/>
        public string trescKomunikatu {
            get {
                return this.trescKomunikatuField;
            }
            set {
                this.trescKomunikatuField = value;
            }
        }
        
        /// <remarks/>
        public long kodKomunikatu {
            get {
                return this.kodKomunikatuField;
            }
            set {
                this.kodKomunikatuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UkladyKart {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pokoj {
        
        private string nazwaPokojuField;
        
        private long numerPokojuField;
        
        private int iloscGraczyMaxField;
        
        private int iloscGraczyObecnaField;
        
        private bool graRozpoczetaField;
        
        private long stawkaWejsciowaField;
        
        private long duzyBlindField;
        
        private long ktoBlindField;
        
        private long stawiaField;
        
        private long obecnaStawkaField;
        
        private Uzytkownik[] userField;
        
        private Karta[] stolField;
        
        private UkladyKart uklField;
        
        /// <remarks/>
        public string nazwaPokoju {
            get {
                return this.nazwaPokojuField;
            }
            set {
                this.nazwaPokojuField = value;
            }
        }
        
        /// <remarks/>
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                this.numerPokojuField = value;
            }
        }
        
        /// <remarks/>
        public int iloscGraczyMax {
            get {
                return this.iloscGraczyMaxField;
            }
            set {
                this.iloscGraczyMaxField = value;
            }
        }
        
        /// <remarks/>
        public int iloscGraczyObecna {
            get {
                return this.iloscGraczyObecnaField;
            }
            set {
                this.iloscGraczyObecnaField = value;
            }
        }
        
        /// <remarks/>
        public bool graRozpoczeta {
            get {
                return this.graRozpoczetaField;
            }
            set {
                this.graRozpoczetaField = value;
            }
        }
        
        /// <remarks/>
        public long stawkaWejsciowa {
            get {
                return this.stawkaWejsciowaField;
            }
            set {
                this.stawkaWejsciowaField = value;
            }
        }
        
        /// <remarks/>
        public long duzyBlind {
            get {
                return this.duzyBlindField;
            }
            set {
                this.duzyBlindField = value;
            }
        }
        
        /// <remarks/>
        public long ktoBlind {
            get {
                return this.ktoBlindField;
            }
            set {
                this.ktoBlindField = value;
            }
        }
        
        /// <remarks/>
        public long stawia {
            get {
                return this.stawiaField;
            }
            set {
                this.stawiaField = value;
            }
        }
        
        /// <remarks/>
        public long obecnaStawka {
            get {
                return this.obecnaStawkaField;
            }
            set {
                this.obecnaStawkaField = value;
            }
        }
        
        /// <remarks/>
        public Uzytkownik[] user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] stol {
            get {
                return this.stolField;
            }
            set {
                this.stolField = value;
            }
        }
        
        /// <remarks/>
        public UkladyKart ukl {
            get {
                return this.uklField;
            }
            set {
                this.uklField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void listaUzytkownikowCompletedEventHandler(object sender, listaUzytkownikowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaUzytkownikowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaUzytkownikowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Uzytkownik[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Uzytkownik[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void KtoWygralCompletedEventHandler(object sender, KtoWygralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KtoWygralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KtoWygralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Uzytkownik[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Uzytkownik[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void naStoleCompletedEventHandler(object sender, naStoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class naStoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal naStoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Karta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Karta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void genCompletedEventHandler(object sender, genCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class genCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal genCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzPokojeCompletedEventHandler(object sender, PobierzPokojeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzPokojeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzPokojeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pokoj[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pokoj[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DolaczDoStoluCompletedEventHandler(object sender, DolaczDoStoluCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DolaczDoStoluCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DolaczDoStoluCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OpuscStolCompletedEventHandler(object sender, OpuscStolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpuscStolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpuscStolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UtworzStolCompletedEventHandler(object sender, UtworzStolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UtworzStolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UtworzStolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzStanStoluCompletedEventHandler(object sender, PobierzStanStoluCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzStanStoluCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzStanStoluCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Akcja[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Akcja[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void WyslijRuchCompletedEventHandler(object sender, WyslijRuchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WyslijRuchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WyslijRuchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void StartCompletedEventHandler(object sender, StartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591