//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace ClientWindowsFormsApplication1.Rozgrywki {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RozgrywkiSoap", Namespace="http://tempuri.org/")]
    public partial class Rozgrywki : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NazwaMojegoUkladuOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzGraczaOperationCompleted;
        
        private System.Threading.SendOrPostCallback zwrocStolOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzPokojeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DolaczDoStoluOperationCompleted;
        
        private System.Threading.SendOrPostCallback UtworzStolOperationCompleted;
        
        private System.Threading.SendOrPostCallback OpuscStolOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzKartyOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartOperationCompleted;
        
        private System.Threading.SendOrPostCallback FoldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallRiseAllInOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZwrocGreOperationCompleted;
        
        private System.Threading.SendOrPostCallback CzyscStolyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Rozgrywki() {
            this.Url = global::ClientWindowsFormsApplication1.Properties.Settings.Default.ClientWindowsFormsApplication1_Rozgrywki_Rozgrywki;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NazwaMojegoUkladuCompletedEventHandler NazwaMojegoUkladuCompleted;
        
        /// <remarks/>
        public event PobierzGraczaCompletedEventHandler PobierzGraczaCompleted;
        
        /// <remarks/>
        public event zwrocStolCompletedEventHandler zwrocStolCompleted;
        
        /// <remarks/>
        public event PobierzPokojeCompletedEventHandler PobierzPokojeCompleted;
        
        /// <remarks/>
        public event DolaczDoStoluCompletedEventHandler DolaczDoStoluCompleted;
        
        /// <remarks/>
        public event UtworzStolCompletedEventHandler UtworzStolCompleted;
        
        /// <remarks/>
        public event OpuscStolCompletedEventHandler OpuscStolCompleted;
        
        /// <remarks/>
        public event PobierzKartyCompletedEventHandler PobierzKartyCompleted;
        
        /// <remarks/>
        public event StartCompletedEventHandler StartCompleted;
        
        /// <remarks/>
        public event FoldCompletedEventHandler FoldCompleted;
        
        /// <remarks/>
        public event CallRiseAllInCompletedEventHandler CallRiseAllInCompleted;
        
        /// <remarks/>
        public event ZwrocGreCompletedEventHandler ZwrocGreCompleted;
        
        /// <remarks/>
        public event CzyscStolyCompletedEventHandler CzyscStolyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NazwaMojegoUkladu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NazwaMojegoUkladu([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("NazwaMojegoUkladu", new object[] {
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NazwaMojegoUkladuAsync(byte[] token) {
            this.NazwaMojegoUkladuAsync(token, null);
        }
        
        /// <remarks/>
        public void NazwaMojegoUkladuAsync(byte[] token, object userState) {
            if ((this.NazwaMojegoUkladuOperationCompleted == null)) {
                this.NazwaMojegoUkladuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNazwaMojegoUkladuOperationCompleted);
            }
            this.InvokeAsync("NazwaMojegoUkladu", new object[] {
                        token}, this.NazwaMojegoUkladuOperationCompleted, userState);
        }
        
        private void OnNazwaMojegoUkladuOperationCompleted(object arg) {
            if ((this.NazwaMojegoUkladuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NazwaMojegoUkladuCompleted(this, new NazwaMojegoUkladuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzGracza", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Gracz PobierzGracza([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token, long mojID) {
            object[] results = this.Invoke("PobierzGracza", new object[] {
                        token,
                        mojID});
            return ((Gracz)(results[0]));
        }
        
        /// <remarks/>
        public void PobierzGraczaAsync(byte[] token, long mojID) {
            this.PobierzGraczaAsync(token, mojID, null);
        }
        
        /// <remarks/>
        public void PobierzGraczaAsync(byte[] token, long mojID, object userState) {
            if ((this.PobierzGraczaOperationCompleted == null)) {
                this.PobierzGraczaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzGraczaOperationCompleted);
            }
            this.InvokeAsync("PobierzGracza", new object[] {
                        token,
                        mojID}, this.PobierzGraczaOperationCompleted, userState);
        }
        
        private void OnPobierzGraczaOperationCompleted(object arg) {
            if ((this.PobierzGraczaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzGraczaCompleted(this, new PobierzGraczaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/zwrocStol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Karta[] zwrocStol([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("zwrocStol", new object[] {
                        token});
            return ((Karta[])(results[0]));
        }
        
        /// <remarks/>
        public void zwrocStolAsync(byte[] token) {
            this.zwrocStolAsync(token, null);
        }
        
        /// <remarks/>
        public void zwrocStolAsync(byte[] token, object userState) {
            if ((this.zwrocStolOperationCompleted == null)) {
                this.zwrocStolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnzwrocStolOperationCompleted);
            }
            this.InvokeAsync("zwrocStol", new object[] {
                        token}, this.zwrocStolOperationCompleted, userState);
        }
        
        private void OnzwrocStolOperationCompleted(object arg) {
            if ((this.zwrocStolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.zwrocStolCompleted(this, new zwrocStolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzPokoje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pokoj[] PobierzPokoje([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("PobierzPokoje", new object[] {
                        token});
            return ((Pokoj[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzPokojeAsync(byte[] token) {
            this.PobierzPokojeAsync(token, null);
        }
        
        /// <remarks/>
        public void PobierzPokojeAsync(byte[] token, object userState) {
            if ((this.PobierzPokojeOperationCompleted == null)) {
                this.PobierzPokojeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzPokojeOperationCompleted);
            }
            this.InvokeAsync("PobierzPokoje", new object[] {
                        token}, this.PobierzPokojeOperationCompleted, userState);
        }
        
        private void OnPobierzPokojeOperationCompleted(object arg) {
            if ((this.PobierzPokojeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzPokojeCompleted(this, new PobierzPokojeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DolaczDoStolu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat DolaczDoStolu([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token, long id) {
            object[] results = this.Invoke("DolaczDoStolu", new object[] {
                        token,
                        id});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void DolaczDoStoluAsync(byte[] token, long id) {
            this.DolaczDoStoluAsync(token, id, null);
        }
        
        /// <remarks/>
        public void DolaczDoStoluAsync(byte[] token, long id, object userState) {
            if ((this.DolaczDoStoluOperationCompleted == null)) {
                this.DolaczDoStoluOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDolaczDoStoluOperationCompleted);
            }
            this.InvokeAsync("DolaczDoStolu", new object[] {
                        token,
                        id}, this.DolaczDoStoluOperationCompleted, userState);
        }
        
        private void OnDolaczDoStoluOperationCompleted(object arg) {
            if ((this.DolaczDoStoluCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DolaczDoStoluCompleted(this, new DolaczDoStoluCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UtworzStol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat UtworzStol([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token, string nazwa, int stawka, int blind, int ilosc) {
            object[] results = this.Invoke("UtworzStol", new object[] {
                        token,
                        nazwa,
                        stawka,
                        blind,
                        ilosc});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void UtworzStolAsync(byte[] token, string nazwa, int stawka, int blind, int ilosc) {
            this.UtworzStolAsync(token, nazwa, stawka, blind, ilosc, null);
        }
        
        /// <remarks/>
        public void UtworzStolAsync(byte[] token, string nazwa, int stawka, int blind, int ilosc, object userState) {
            if ((this.UtworzStolOperationCompleted == null)) {
                this.UtworzStolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUtworzStolOperationCompleted);
            }
            this.InvokeAsync("UtworzStol", new object[] {
                        token,
                        nazwa,
                        stawka,
                        blind,
                        ilosc}, this.UtworzStolOperationCompleted, userState);
        }
        
        private void OnUtworzStolOperationCompleted(object arg) {
            if ((this.UtworzStolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UtworzStolCompleted(this, new UtworzStolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OpuscStol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat OpuscStol([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("OpuscStol", new object[] {
                        token});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void OpuscStolAsync(byte[] token) {
            this.OpuscStolAsync(token, null);
        }
        
        /// <remarks/>
        public void OpuscStolAsync(byte[] token, object userState) {
            if ((this.OpuscStolOperationCompleted == null)) {
                this.OpuscStolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpuscStolOperationCompleted);
            }
            this.InvokeAsync("OpuscStol", new object[] {
                        token}, this.OpuscStolOperationCompleted, userState);
        }
        
        private void OnOpuscStolOperationCompleted(object arg) {
            if ((this.OpuscStolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpuscStolCompleted(this, new OpuscStolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzKarty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Karta[] PobierzKarty([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("PobierzKarty", new object[] {
                        token});
            return ((Karta[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzKartyAsync(byte[] token) {
            this.PobierzKartyAsync(token, null);
        }
        
        /// <remarks/>
        public void PobierzKartyAsync(byte[] token, object userState) {
            if ((this.PobierzKartyOperationCompleted == null)) {
                this.PobierzKartyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzKartyOperationCompleted);
            }
            this.InvokeAsync("PobierzKarty", new object[] {
                        token}, this.PobierzKartyOperationCompleted, userState);
        }
        
        private void OnPobierzKartyOperationCompleted(object arg) {
            if ((this.PobierzKartyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzKartyCompleted(this, new PobierzKartyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Start", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat Start([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("Start", new object[] {
                        token});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void StartAsync(byte[] token) {
            this.StartAsync(token, null);
        }
        
        /// <remarks/>
        public void StartAsync(byte[] token, object userState) {
            if ((this.StartOperationCompleted == null)) {
                this.StartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartOperationCompleted);
            }
            this.InvokeAsync("Start", new object[] {
                        token}, this.StartOperationCompleted, userState);
        }
        
        private void OnStartOperationCompleted(object arg) {
            if ((this.StartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartCompleted(this, new StartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fold", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat Fold([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("Fold", new object[] {
                        token});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void FoldAsync(byte[] token) {
            this.FoldAsync(token, null);
        }
        
        /// <remarks/>
        public void FoldAsync(byte[] token, object userState) {
            if ((this.FoldOperationCompleted == null)) {
                this.FoldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFoldOperationCompleted);
            }
            this.InvokeAsync("Fold", new object[] {
                        token}, this.FoldOperationCompleted, userState);
        }
        
        private void OnFoldOperationCompleted(object arg) {
            if ((this.FoldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FoldCompleted(this, new FoldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CallRiseAllIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat CallRiseAllIn([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token, long ile) {
            object[] results = this.Invoke("CallRiseAllIn", new object[] {
                        token,
                        ile});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void CallRiseAllInAsync(byte[] token, long ile) {
            this.CallRiseAllInAsync(token, ile, null);
        }
        
        /// <remarks/>
        public void CallRiseAllInAsync(byte[] token, long ile, object userState) {
            if ((this.CallRiseAllInOperationCompleted == null)) {
                this.CallRiseAllInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallRiseAllInOperationCompleted);
            }
            this.InvokeAsync("CallRiseAllIn", new object[] {
                        token,
                        ile}, this.CallRiseAllInOperationCompleted, userState);
        }
        
        private void OnCallRiseAllInOperationCompleted(object arg) {
            if ((this.CallRiseAllInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallRiseAllInCompleted(this, new CallRiseAllInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ZwrocGre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Gra ZwrocGre([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("ZwrocGre", new object[] {
                        token});
            return ((Gra)(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocGreAsync(byte[] token) {
            this.ZwrocGreAsync(token, null);
        }
        
        /// <remarks/>
        public void ZwrocGreAsync(byte[] token, object userState) {
            if ((this.ZwrocGreOperationCompleted == null)) {
                this.ZwrocGreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocGreOperationCompleted);
            }
            this.InvokeAsync("ZwrocGre", new object[] {
                        token}, this.ZwrocGreOperationCompleted, userState);
        }
        
        private void OnZwrocGreOperationCompleted(object arg) {
            if ((this.ZwrocGreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocGreCompleted(this, new ZwrocGreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CzyscStoly", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CzyscStoly() {
            this.Invoke("CzyscStoly", new object[0]);
        }
        
        /// <remarks/>
        public void CzyscStolyAsync() {
            this.CzyscStolyAsync(null);
        }
        
        /// <remarks/>
        public void CzyscStolyAsync(object userState) {
            if ((this.CzyscStolyOperationCompleted == null)) {
                this.CzyscStolyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCzyscStolyOperationCompleted);
            }
            this.InvokeAsync("CzyscStoly", new object[0], this.CzyscStolyOperationCompleted, userState);
        }
        
        private void OnCzyscStolyOperationCompleted(object arg) {
            if ((this.CzyscStolyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CzyscStolyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Gracz : Uzytkownik {
        
        private int kickerField;
        
        private Karta[] handWinField;
        
        private Karta[] najUkladWinField;
        
        private StanGracza stanField;
        
        private int wartField;
        
        private string nazwaUkladuField;
        
        private bool czyPobralKartyField;
        
        private long kasaField;
        
        private long stawiaField;
        
        /// <remarks/>
        public int kicker {
            get {
                return this.kickerField;
            }
            set {
                this.kickerField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] handWin {
            get {
                return this.handWinField;
            }
            set {
                this.handWinField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] najUkladWin {
            get {
                return this.najUkladWinField;
            }
            set {
                this.najUkladWinField = value;
            }
        }
        
        /// <remarks/>
        public StanGracza stan {
            get {
                return this.stanField;
            }
            set {
                this.stanField = value;
            }
        }
        
        /// <remarks/>
        public int wart {
            get {
                return this.wartField;
            }
            set {
                this.wartField = value;
            }
        }
        
        /// <remarks/>
        public string nazwaUkladu {
            get {
                return this.nazwaUkladuField;
            }
            set {
                this.nazwaUkladuField = value;
            }
        }
        
        /// <remarks/>
        public bool czyPobralKarty {
            get {
                return this.czyPobralKartyField;
            }
            set {
                this.czyPobralKartyField = value;
            }
        }
        
        /// <remarks/>
        public long kasa {
            get {
                return this.kasaField;
            }
            set {
                this.kasaField = value;
            }
        }
        
        /// <remarks/>
        public long stawia {
            get {
                return this.stawiaField;
            }
            set {
                this.stawiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Karta {
        
        private figuraKarty figuraField;
        
        private kolorKarty kolorField;
        
        /// <remarks/>
        public figuraKarty figura {
            get {
                return this.figuraField;
            }
            set {
                this.figuraField = value;
            }
        }
        
        /// <remarks/>
        public kolorKarty kolor {
            get {
                return this.kolorField;
            }
            set {
                this.kolorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum figuraKarty {
        
        /// <remarks/>
        K2,
        
        /// <remarks/>
        K3,
        
        /// <remarks/>
        K4,
        
        /// <remarks/>
        K5,
        
        /// <remarks/>
        K6,
        
        /// <remarks/>
        K7,
        
        /// <remarks/>
        K8,
        
        /// <remarks/>
        K9,
        
        /// <remarks/>
        K10,
        
        /// <remarks/>
        KJ,
        
        /// <remarks/>
        KD,
        
        /// <remarks/>
        KK,
        
        /// <remarks/>
        KA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum kolorKarty {
        
        /// <remarks/>
        pik,
        
        /// <remarks/>
        kier,
        
        /// <remarks/>
        karo,
        
        /// <remarks/>
        trefl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Gra {
        
        private Gracz[] userField;
        
        private Gracz[] aktywniField;
        
        private Stan stanField;
        
        private long ktoBigBlindField;
        
        private long ktoStawiaField;
        
        private long czyjRuchField;
        
        private long najwyzszaStawkaField;
        
        private long pulaField;
        
        private long duzyBlindField;
        
        private Karta[] stolField;
        
        /// <remarks/>
        public Gracz[] user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public Gracz[] aktywni {
            get {
                return this.aktywniField;
            }
            set {
                this.aktywniField = value;
            }
        }
        
        /// <remarks/>
        public Stan stan {
            get {
                return this.stanField;
            }
            set {
                this.stanField = value;
            }
        }
        
        /// <remarks/>
        public long ktoBigBlind {
            get {
                return this.ktoBigBlindField;
            }
            set {
                this.ktoBigBlindField = value;
            }
        }
        
        /// <remarks/>
        public long ktoStawia {
            get {
                return this.ktoStawiaField;
            }
            set {
                this.ktoStawiaField = value;
            }
        }
        
        /// <remarks/>
        public long czyjRuch {
            get {
                return this.czyjRuchField;
            }
            set {
                this.czyjRuchField = value;
            }
        }
        
        /// <remarks/>
        public long najwyzszaStawka {
            get {
                return this.najwyzszaStawkaField;
            }
            set {
                this.najwyzszaStawkaField = value;
            }
        }
        
        /// <remarks/>
        public long pula {
            get {
                return this.pulaField;
            }
            set {
                this.pulaField = value;
            }
        }
        
        /// <remarks/>
        public long duzyBlind {
            get {
                return this.duzyBlindField;
            }
            set {
                this.duzyBlindField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] stol {
            get {
                return this.stolField;
            }
            set {
                this.stolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Stan {
        
        /// <remarks/>
        PREFLOP,
        
        /// <remarks/>
        FLOP,
        
        /// <remarks/>
        TURN,
        
        /// <remarks/>
        RIVER,
        
        /// <remarks/>
        SHOWDOWN,
        
        /// <remarks/>
        STARTING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Komunikat {
        
        private string trescKomunikatuField;
        
        private long kodKomunikatuField;
        
        /// <remarks/>
        public string trescKomunikatu {
            get {
                return this.trescKomunikatuField;
            }
            set {
                this.trescKomunikatuField = value;
            }
        }
        
        /// <remarks/>
        public long kodKomunikatu {
            get {
                return this.kodKomunikatuField;
            }
            set {
                this.kodKomunikatuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pokoj {
        
        private string nazwaPokojuField;
        
        private long numerPokojuField;
        
        private int iloscGraczyMaxField;
        
        private int iloscGraczyObecnaField;
        
        private bool graRozpoczetaField;
        
        private long stawkaWejsciowaField;
        
        private long duzyBlindField;
        
        private Uzytkownik[] userField;
        
        /// <remarks/>
        public string nazwaPokoju {
            get {
                return this.nazwaPokojuField;
            }
            set {
                this.nazwaPokojuField = value;
            }
        }
        
        /// <remarks/>
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                this.numerPokojuField = value;
            }
        }
        
        /// <remarks/>
        public int iloscGraczyMax {
            get {
                return this.iloscGraczyMaxField;
            }
            set {
                this.iloscGraczyMaxField = value;
            }
        }
        
        /// <remarks/>
        public int iloscGraczyObecna {
            get {
                return this.iloscGraczyObecnaField;
            }
            set {
                this.iloscGraczyObecnaField = value;
            }
        }
        
        /// <remarks/>
        public bool graRozpoczeta {
            get {
                return this.graRozpoczetaField;
            }
            set {
                this.graRozpoczetaField = value;
            }
        }
        
        /// <remarks/>
        public long stawkaWejsciowa {
            get {
                return this.stawkaWejsciowaField;
            }
            set {
                this.stawkaWejsciowaField = value;
            }
        }
        
        /// <remarks/>
        public long duzyBlind {
            get {
                return this.duzyBlindField;
            }
            set {
                this.duzyBlindField = value;
            }
        }
        
        /// <remarks/>
        public Uzytkownik[] user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gracz))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Uzytkownik {
        
        private long identyfikatorUzytkownikaField;
        
        private string nazwaUzytkownikaField;
        
        private long numerPokojuField;
        
        private long kasioraField;
        
        private bool foldField;
        
        private bool startField;
        
        /// <remarks/>
        public long identyfikatorUzytkownika {
            get {
                return this.identyfikatorUzytkownikaField;
            }
            set {
                this.identyfikatorUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public string nazwaUzytkownika {
            get {
                return this.nazwaUzytkownikaField;
            }
            set {
                this.nazwaUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                this.numerPokojuField = value;
            }
        }
        
        /// <remarks/>
        public long kasiora {
            get {
                return this.kasioraField;
            }
            set {
                this.kasioraField = value;
            }
        }
        
        /// <remarks/>
        public bool fold {
            get {
                return this.foldField;
            }
            set {
                this.foldField = value;
            }
        }
        
        /// <remarks/>
        public bool start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum StanGracza {
        
        /// <remarks/>
        Fold,
        
        /// <remarks/>
        Call,
        
        /// <remarks/>
        Rise,
        
        /// <remarks/>
        AllIn,
        
        /// <remarks/>
        BigBlind,
        
        /// <remarks/>
        SmallBlind,
        
        /// <remarks/>
        Dealer,
        
        /// <remarks/>
        Ready,
        
        /// <remarks/>
        NotReady,
        
        /// <remarks/>
        Winner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NazwaMojegoUkladuCompletedEventHandler(object sender, NazwaMojegoUkladuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NazwaMojegoUkladuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NazwaMojegoUkladuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzGraczaCompletedEventHandler(object sender, PobierzGraczaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzGraczaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzGraczaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Gracz Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Gracz)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void zwrocStolCompletedEventHandler(object sender, zwrocStolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class zwrocStolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal zwrocStolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Karta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Karta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzPokojeCompletedEventHandler(object sender, PobierzPokojeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzPokojeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzPokojeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pokoj[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pokoj[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DolaczDoStoluCompletedEventHandler(object sender, DolaczDoStoluCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DolaczDoStoluCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DolaczDoStoluCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UtworzStolCompletedEventHandler(object sender, UtworzStolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UtworzStolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UtworzStolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OpuscStolCompletedEventHandler(object sender, OpuscStolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpuscStolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpuscStolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzKartyCompletedEventHandler(object sender, PobierzKartyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzKartyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzKartyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Karta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Karta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void StartCompletedEventHandler(object sender, StartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FoldCompletedEventHandler(object sender, FoldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FoldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FoldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallRiseAllInCompletedEventHandler(object sender, CallRiseAllInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallRiseAllInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallRiseAllInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ZwrocGreCompletedEventHandler(object sender, ZwrocGreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocGreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocGreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Gra Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Gra)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CzyscStolyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591