//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace ClientWindowsFormsApplication1.Glowny {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GlownySoap", Namespace="http://tempuri.org/")]
    public partial class Glowny : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZwrocZalogowanychOperationCompleted;
        
        private System.Threading.SendOrPostCallback dodajZwOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZarejestrujOperationCompleted;
        
        private System.Threading.SendOrPostCallback SprawdzNazweOperationCompleted;
        
        private System.Threading.SendOrPostCallback SprawdzEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZalogujOperationCompleted;
        
        private System.Threading.SendOrPostCallback WylogujOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzSwojeIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzUzytkownikowOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzWiadomosciOperationCompleted;
        
        private System.Threading.SendOrPostCallback WyslijWiadomoscOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Glowny() {
            this.Url = global::ClientWindowsFormsApplication1.Properties.Settings.Default.ClientWindowsFormsApplication1_Glowny_Glowny;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZwrocZalogowanychCompletedEventHandler ZwrocZalogowanychCompleted;
        
        /// <remarks/>
        public event dodajZwCompletedEventHandler dodajZwCompleted;
        
        /// <remarks/>
        public event ZarejestrujCompletedEventHandler ZarejestrujCompleted;
        
        /// <remarks/>
        public event SprawdzNazweCompletedEventHandler SprawdzNazweCompleted;
        
        /// <remarks/>
        public event SprawdzEmailCompletedEventHandler SprawdzEmailCompleted;
        
        /// <remarks/>
        public event ZalogujCompletedEventHandler ZalogujCompleted;
        
        /// <remarks/>
        public event WylogujCompletedEventHandler WylogujCompleted;
        
        /// <remarks/>
        public event PobierzSwojeIDCompletedEventHandler PobierzSwojeIDCompleted;
        
        /// <remarks/>
        public event PobierzUzytkownikowCompletedEventHandler PobierzUzytkownikowCompleted;
        
        /// <remarks/>
        public event PobierzWiadomosciCompletedEventHandler PobierzWiadomosciCompleted;
        
        /// <remarks/>
        public event WyslijWiadomoscCompletedEventHandler WyslijWiadomoscCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ZwrocZalogowanych", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Uzytkownik[] ZwrocZalogowanych() {
            object[] results = this.Invoke("ZwrocZalogowanych", new object[0]);
            return ((Uzytkownik[])(results[0]));
        }
        
        /// <remarks/>
        public void ZwrocZalogowanychAsync() {
            this.ZwrocZalogowanychAsync(null);
        }
        
        /// <remarks/>
        public void ZwrocZalogowanychAsync(object userState) {
            if ((this.ZwrocZalogowanychOperationCompleted == null)) {
                this.ZwrocZalogowanychOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwrocZalogowanychOperationCompleted);
            }
            this.InvokeAsync("ZwrocZalogowanych", new object[0], this.ZwrocZalogowanychOperationCompleted, userState);
        }
        
        private void OnZwrocZalogowanychOperationCompleted(object arg) {
            if ((this.ZwrocZalogowanychCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwrocZalogowanychCompleted(this, new ZwrocZalogowanychCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dodajZw", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool dodajZw() {
            object[] results = this.Invoke("dodajZw", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void dodajZwAsync() {
            this.dodajZwAsync(null);
        }
        
        /// <remarks/>
        public void dodajZwAsync(object userState) {
            if ((this.dodajZwOperationCompleted == null)) {
                this.dodajZwOperationCompleted = new System.Threading.SendOrPostCallback(this.OndodajZwOperationCompleted);
            }
            this.InvokeAsync("dodajZw", new object[0], this.dodajZwOperationCompleted, userState);
        }
        
        private void OndodajZwOperationCompleted(object arg) {
            if ((this.dodajZwCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dodajZwCompleted(this, new dodajZwCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Zarejestruj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat Zarejestruj(string nazwa, string haslo, string email) {
            object[] results = this.Invoke("Zarejestruj", new object[] {
                        nazwa,
                        haslo,
                        email});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void ZarejestrujAsync(string nazwa, string haslo, string email) {
            this.ZarejestrujAsync(nazwa, haslo, email, null);
        }
        
        /// <remarks/>
        public void ZarejestrujAsync(string nazwa, string haslo, string email, object userState) {
            if ((this.ZarejestrujOperationCompleted == null)) {
                this.ZarejestrujOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZarejestrujOperationCompleted);
            }
            this.InvokeAsync("Zarejestruj", new object[] {
                        nazwa,
                        haslo,
                        email}, this.ZarejestrujOperationCompleted, userState);
        }
        
        private void OnZarejestrujOperationCompleted(object arg) {
            if ((this.ZarejestrujCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZarejestrujCompleted(this, new ZarejestrujCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SprawdzNazwe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat SprawdzNazwe(string nazwa) {
            object[] results = this.Invoke("SprawdzNazwe", new object[] {
                        nazwa});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void SprawdzNazweAsync(string nazwa) {
            this.SprawdzNazweAsync(nazwa, null);
        }
        
        /// <remarks/>
        public void SprawdzNazweAsync(string nazwa, object userState) {
            if ((this.SprawdzNazweOperationCompleted == null)) {
                this.SprawdzNazweOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSprawdzNazweOperationCompleted);
            }
            this.InvokeAsync("SprawdzNazwe", new object[] {
                        nazwa}, this.SprawdzNazweOperationCompleted, userState);
        }
        
        private void OnSprawdzNazweOperationCompleted(object arg) {
            if ((this.SprawdzNazweCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SprawdzNazweCompleted(this, new SprawdzNazweCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SprawdzEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat SprawdzEmail(string email) {
            object[] results = this.Invoke("SprawdzEmail", new object[] {
                        email});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void SprawdzEmailAsync(string email) {
            this.SprawdzEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void SprawdzEmailAsync(string email, object userState) {
            if ((this.SprawdzEmailOperationCompleted == null)) {
                this.SprawdzEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSprawdzEmailOperationCompleted);
            }
            this.InvokeAsync("SprawdzEmail", new object[] {
                        email}, this.SprawdzEmailOperationCompleted, userState);
        }
        
        private void OnSprawdzEmailOperationCompleted(object arg) {
            if ((this.SprawdzEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SprawdzEmailCompleted(this, new SprawdzEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Zaloguj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Zaloguj(string nazwa, string haslo) {
            object[] results = this.Invoke("Zaloguj", new object[] {
                        nazwa,
                        haslo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ZalogujAsync(string nazwa, string haslo) {
            this.ZalogujAsync(nazwa, haslo, null);
        }
        
        /// <remarks/>
        public void ZalogujAsync(string nazwa, string haslo, object userState) {
            if ((this.ZalogujOperationCompleted == null)) {
                this.ZalogujOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZalogujOperationCompleted);
            }
            this.InvokeAsync("Zaloguj", new object[] {
                        nazwa,
                        haslo}, this.ZalogujOperationCompleted, userState);
        }
        
        private void OnZalogujOperationCompleted(object arg) {
            if ((this.ZalogujCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZalogujCompleted(this, new ZalogujCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Wyloguj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat Wyloguj([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("Wyloguj", new object[] {
                        token});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void WylogujAsync(byte[] token) {
            this.WylogujAsync(token, null);
        }
        
        /// <remarks/>
        public void WylogujAsync(byte[] token, object userState) {
            if ((this.WylogujOperationCompleted == null)) {
                this.WylogujOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWylogujOperationCompleted);
            }
            this.InvokeAsync("Wyloguj", new object[] {
                        token}, this.WylogujOperationCompleted, userState);
        }
        
        private void OnWylogujOperationCompleted(object arg) {
            if ((this.WylogujCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WylogujCompleted(this, new WylogujCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzSwojeID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat PobierzSwojeID([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("PobierzSwojeID", new object[] {
                        token});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void PobierzSwojeIDAsync(byte[] token) {
            this.PobierzSwojeIDAsync(token, null);
        }
        
        /// <remarks/>
        public void PobierzSwojeIDAsync(byte[] token, object userState) {
            if ((this.PobierzSwojeIDOperationCompleted == null)) {
                this.PobierzSwojeIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzSwojeIDOperationCompleted);
            }
            this.InvokeAsync("PobierzSwojeID", new object[] {
                        token}, this.PobierzSwojeIDOperationCompleted, userState);
        }
        
        private void OnPobierzSwojeIDOperationCompleted(object arg) {
            if ((this.PobierzSwojeIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzSwojeIDCompleted(this, new PobierzSwojeIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzUzytkownikow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Uzytkownik[] PobierzUzytkownikow([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token) {
            object[] results = this.Invoke("PobierzUzytkownikow", new object[] {
                        token});
            return ((Uzytkownik[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzUzytkownikowAsync(byte[] token) {
            this.PobierzUzytkownikowAsync(token, null);
        }
        
        /// <remarks/>
        public void PobierzUzytkownikowAsync(byte[] token, object userState) {
            if ((this.PobierzUzytkownikowOperationCompleted == null)) {
                this.PobierzUzytkownikowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzUzytkownikowOperationCompleted);
            }
            this.InvokeAsync("PobierzUzytkownikow", new object[] {
                        token}, this.PobierzUzytkownikowOperationCompleted, userState);
        }
        
        private void OnPobierzUzytkownikowOperationCompleted(object arg) {
            if ((this.PobierzUzytkownikowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzUzytkownikowCompleted(this, new PobierzUzytkownikowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzWiadomosci", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Wiadomosc[] PobierzWiadomosci([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token, int timT, long pokoj) {
            object[] results = this.Invoke("PobierzWiadomosci", new object[] {
                        token,
                        timT,
                        pokoj});
            return ((Wiadomosc[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzWiadomosciAsync(byte[] token, int timT, long pokoj) {
            this.PobierzWiadomosciAsync(token, timT, pokoj, null);
        }
        
        /// <remarks/>
        public void PobierzWiadomosciAsync(byte[] token, int timT, long pokoj, object userState) {
            if ((this.PobierzWiadomosciOperationCompleted == null)) {
                this.PobierzWiadomosciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzWiadomosciOperationCompleted);
            }
            this.InvokeAsync("PobierzWiadomosci", new object[] {
                        token,
                        timT,
                        pokoj}, this.PobierzWiadomosciOperationCompleted, userState);
        }
        
        private void OnPobierzWiadomosciOperationCompleted(object arg) {
            if ((this.PobierzWiadomosciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzWiadomosciCompleted(this, new PobierzWiadomosciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WyslijWiadomosc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat WyslijWiadomosc([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] token, Wiadomosc wiadomosc) {
            object[] results = this.Invoke("WyslijWiadomosc", new object[] {
                        token,
                        wiadomosc});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void WyslijWiadomoscAsync(byte[] token, Wiadomosc wiadomosc) {
            this.WyslijWiadomoscAsync(token, wiadomosc, null);
        }
        
        /// <remarks/>
        public void WyslijWiadomoscAsync(byte[] token, Wiadomosc wiadomosc, object userState) {
            if ((this.WyslijWiadomoscOperationCompleted == null)) {
                this.WyslijWiadomoscOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWyslijWiadomoscOperationCompleted);
            }
            this.InvokeAsync("WyslijWiadomosc", new object[] {
                        token,
                        wiadomosc}, this.WyslijWiadomoscOperationCompleted, userState);
        }
        
        private void OnWyslijWiadomoscOperationCompleted(object arg) {
            if ((this.WyslijWiadomoscCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WyslijWiadomoscCompleted(this, new WyslijWiadomoscCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Uzytkownik {
        
        private long identyfikatorUzytkownikaField;
        
        private string nazwaUzytkownikaField;
        
        private long numerPokojuField;
        
        private long kasioraField;
        
        private bool foldField;
        
        private bool startField;
        
        /// <remarks/>
        public long identyfikatorUzytkownika {
            get {
                return this.identyfikatorUzytkownikaField;
            }
            set {
                this.identyfikatorUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public string nazwaUzytkownika {
            get {
                return this.nazwaUzytkownikaField;
            }
            set {
                this.nazwaUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                this.numerPokojuField = value;
            }
        }
        
        /// <remarks/>
        public long kasiora {
            get {
                return this.kasioraField;
            }
            set {
                this.kasioraField = value;
            }
        }
        
        /// <remarks/>
        public bool fold {
            get {
                return this.foldField;
            }
            set {
                this.foldField = value;
            }
        }
        
        /// <remarks/>
        public bool start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Wiadomosc {
        
        private string nazwaUzytkownikaField;
        
        private string trescWiadomosciField;
        
        private int stempelCzasowyField;
        
        private long numerPokojuField;
        
        /// <remarks/>
        public string nazwaUzytkownika {
            get {
                return this.nazwaUzytkownikaField;
            }
            set {
                this.nazwaUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public string trescWiadomosci {
            get {
                return this.trescWiadomosciField;
            }
            set {
                this.trescWiadomosciField = value;
            }
        }
        
        /// <remarks/>
        public int stempelCzasowy {
            get {
                return this.stempelCzasowyField;
            }
            set {
                this.stempelCzasowyField = value;
            }
        }
        
        /// <remarks/>
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                this.numerPokojuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Komunikat {
        
        private string trescKomunikatuField;
        
        private long kodKomunikatuField;
        
        /// <remarks/>
        public string trescKomunikatu {
            get {
                return this.trescKomunikatuField;
            }
            set {
                this.trescKomunikatuField = value;
            }
        }
        
        /// <remarks/>
        public long kodKomunikatu {
            get {
                return this.kodKomunikatuField;
            }
            set {
                this.kodKomunikatuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ZwrocZalogowanychCompletedEventHandler(object sender, ZwrocZalogowanychCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwrocZalogowanychCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwrocZalogowanychCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Uzytkownik[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Uzytkownik[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void dodajZwCompletedEventHandler(object sender, dodajZwCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dodajZwCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dodajZwCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ZarejestrujCompletedEventHandler(object sender, ZarejestrujCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZarejestrujCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZarejestrujCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SprawdzNazweCompletedEventHandler(object sender, SprawdzNazweCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SprawdzNazweCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SprawdzNazweCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SprawdzEmailCompletedEventHandler(object sender, SprawdzEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SprawdzEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SprawdzEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ZalogujCompletedEventHandler(object sender, ZalogujCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZalogujCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZalogujCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void WylogujCompletedEventHandler(object sender, WylogujCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WylogujCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WylogujCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzSwojeIDCompletedEventHandler(object sender, PobierzSwojeIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzSwojeIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzSwojeIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzUzytkownikowCompletedEventHandler(object sender, PobierzUzytkownikowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzUzytkownikowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzUzytkownikowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Uzytkownik[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Uzytkownik[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzWiadomosciCompletedEventHandler(object sender, PobierzWiadomosciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzWiadomosciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzWiadomosciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Wiadomosc[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Wiadomosc[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void WyslijWiadomoscCompletedEventHandler(object sender, WyslijWiadomoscCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WyslijWiadomoscCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WyslijWiadomoscCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591