//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace ClientWindowsFormsApplication1.Glowny {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GlownySoap", Namespace="http://tempuri.org/")]
    public partial class Glowny : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZarejestrujOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZalogujOperationCompleted;
        
        private System.Threading.SendOrPostCallback WylogujOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZmienHasloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetujHasloOperationCompleted;
        
        private System.Threading.SendOrPostCallback UsunKontoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzTokenyOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzUzytkownikowOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzWiadomosciOperationCompleted;
        
        private System.Threading.SendOrPostCallback WyslijWiadomoscOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Glowny() {
            this.Url = global::ClientWindowsFormsApplication1.Properties.Settings.Default.ClientWindowsFormsApplication1_Glowny_Glowny;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ZarejestrujCompletedEventHandler ZarejestrujCompleted;
        
        /// <remarks/>
        public event ZalogujCompletedEventHandler ZalogujCompleted;
        
        /// <remarks/>
        public event WylogujCompletedEventHandler WylogujCompleted;
        
        /// <remarks/>
        public event ZmienHasloCompletedEventHandler ZmienHasloCompleted;
        
        /// <remarks/>
        public event ResetujHasloCompletedEventHandler ResetujHasloCompleted;
        
        /// <remarks/>
        public event UsunKontoCompletedEventHandler UsunKontoCompleted;
        
        /// <remarks/>
        public event PobierzTokenyCompletedEventHandler PobierzTokenyCompleted;
        
        /// <remarks/>
        public event PobierzUzytkownikowCompletedEventHandler PobierzUzytkownikowCompleted;
        
        /// <remarks/>
        public event PobierzWiadomosciCompletedEventHandler PobierzWiadomosciCompleted;
        
        /// <remarks/>
        public event WyslijWiadomoscCompletedEventHandler WyslijWiadomoscCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Zarejestruj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat Zarejestruj(string nazwa, string haslo, string email) {
            object[] results = this.Invoke("Zarejestruj", new object[] {
                        nazwa,
                        haslo,
                        email});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void ZarejestrujAsync(string nazwa, string haslo, string email) {
            this.ZarejestrujAsync(nazwa, haslo, email, null);
        }
        
        /// <remarks/>
        public void ZarejestrujAsync(string nazwa, string haslo, string email, object userState) {
            if ((this.ZarejestrujOperationCompleted == null)) {
                this.ZarejestrujOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZarejestrujOperationCompleted);
            }
            this.InvokeAsync("Zarejestruj", new object[] {
                        nazwa,
                        haslo,
                        email}, this.ZarejestrujOperationCompleted, userState);
        }
        
        private void OnZarejestrujOperationCompleted(object arg) {
            if ((this.ZarejestrujCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZarejestrujCompleted(this, new ZarejestrujCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Zaloguj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat Zaloguj(string nazwa, string haslo) {
            object[] results = this.Invoke("Zaloguj", new object[] {
                        nazwa,
                        haslo});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void ZalogujAsync(string nazwa, string haslo) {
            this.ZalogujAsync(nazwa, haslo, null);
        }
        
        /// <remarks/>
        public void ZalogujAsync(string nazwa, string haslo, object userState) {
            if ((this.ZalogujOperationCompleted == null)) {
                this.ZalogujOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZalogujOperationCompleted);
            }
            this.InvokeAsync("Zaloguj", new object[] {
                        nazwa,
                        haslo}, this.ZalogujOperationCompleted, userState);
        }
        
        private void OnZalogujOperationCompleted(object arg) {
            if ((this.ZalogujCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZalogujCompleted(this, new ZalogujCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Wyloguj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat Wyloguj(string token) {
            object[] results = this.Invoke("Wyloguj", new object[] {
                        token});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void WylogujAsync(string token) {
            this.WylogujAsync(token, null);
        }
        
        /// <remarks/>
        public void WylogujAsync(string token, object userState) {
            if ((this.WylogujOperationCompleted == null)) {
                this.WylogujOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWylogujOperationCompleted);
            }
            this.InvokeAsync("Wyloguj", new object[] {
                        token}, this.WylogujOperationCompleted, userState);
        }
        
        private void OnWylogujOperationCompleted(object arg) {
            if ((this.WylogujCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WylogujCompleted(this, new WylogujCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ZmienHaslo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat ZmienHaslo(string token, string haslo) {
            object[] results = this.Invoke("ZmienHaslo", new object[] {
                        token,
                        haslo});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void ZmienHasloAsync(string token, string haslo) {
            this.ZmienHasloAsync(token, haslo, null);
        }
        
        /// <remarks/>
        public void ZmienHasloAsync(string token, string haslo, object userState) {
            if ((this.ZmienHasloOperationCompleted == null)) {
                this.ZmienHasloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZmienHasloOperationCompleted);
            }
            this.InvokeAsync("ZmienHaslo", new object[] {
                        token,
                        haslo}, this.ZmienHasloOperationCompleted, userState);
        }
        
        private void OnZmienHasloOperationCompleted(object arg) {
            if ((this.ZmienHasloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZmienHasloCompleted(this, new ZmienHasloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetujHaslo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat ResetujHaslo(string email) {
            object[] results = this.Invoke("ResetujHaslo", new object[] {
                        email});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void ResetujHasloAsync(string email) {
            this.ResetujHasloAsync(email, null);
        }
        
        /// <remarks/>
        public void ResetujHasloAsync(string email, object userState) {
            if ((this.ResetujHasloOperationCompleted == null)) {
                this.ResetujHasloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetujHasloOperationCompleted);
            }
            this.InvokeAsync("ResetujHaslo", new object[] {
                        email}, this.ResetujHasloOperationCompleted, userState);
        }
        
        private void OnResetujHasloOperationCompleted(object arg) {
            if ((this.ResetujHasloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetujHasloCompleted(this, new ResetujHasloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UsunKonto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat UsunKonto(string token) {
            object[] results = this.Invoke("UsunKonto", new object[] {
                        token});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void UsunKontoAsync(string token) {
            this.UsunKontoAsync(token, null);
        }
        
        /// <remarks/>
        public void UsunKontoAsync(string token, object userState) {
            if ((this.UsunKontoOperationCompleted == null)) {
                this.UsunKontoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsunKontoOperationCompleted);
            }
            this.InvokeAsync("UsunKonto", new object[] {
                        token}, this.UsunKontoOperationCompleted, userState);
        }
        
        private void OnUsunKontoOperationCompleted(object arg) {
            if ((this.UsunKontoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UsunKontoCompleted(this, new UsunKontoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzTokeny", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Key[] PobierzTokeny() {
            object[] results = this.Invoke("PobierzTokeny", new object[0]);
            return ((Key[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzTokenyAsync() {
            this.PobierzTokenyAsync(null);
        }
        
        /// <remarks/>
        public void PobierzTokenyAsync(object userState) {
            if ((this.PobierzTokenyOperationCompleted == null)) {
                this.PobierzTokenyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzTokenyOperationCompleted);
            }
            this.InvokeAsync("PobierzTokeny", new object[0], this.PobierzTokenyOperationCompleted, userState);
        }
        
        private void OnPobierzTokenyOperationCompleted(object arg) {
            if ((this.PobierzTokenyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzTokenyCompleted(this, new PobierzTokenyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzUzytkownikow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Uzytkownik[] PobierzUzytkownikow(string token) {
            object[] results = this.Invoke("PobierzUzytkownikow", new object[] {
                        token});
            return ((Uzytkownik[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzUzytkownikowAsync(string token) {
            this.PobierzUzytkownikowAsync(token, null);
        }
        
        /// <remarks/>
        public void PobierzUzytkownikowAsync(string token, object userState) {
            if ((this.PobierzUzytkownikowOperationCompleted == null)) {
                this.PobierzUzytkownikowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzUzytkownikowOperationCompleted);
            }
            this.InvokeAsync("PobierzUzytkownikow", new object[] {
                        token}, this.PobierzUzytkownikowOperationCompleted, userState);
        }
        
        private void OnPobierzUzytkownikowOperationCompleted(object arg) {
            if ((this.PobierzUzytkownikowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzUzytkownikowCompleted(this, new PobierzUzytkownikowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PobierzWiadomosci", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Wiadomosc[] PobierzWiadomosci(string token, int timT) {
            object[] results = this.Invoke("PobierzWiadomosci", new object[] {
                        token,
                        timT});
            return ((Wiadomosc[])(results[0]));
        }
        
        /// <remarks/>
        public void PobierzWiadomosciAsync(string token, int timT) {
            this.PobierzWiadomosciAsync(token, timT, null);
        }
        
        /// <remarks/>
        public void PobierzWiadomosciAsync(string token, int timT, object userState) {
            if ((this.PobierzWiadomosciOperationCompleted == null)) {
                this.PobierzWiadomosciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzWiadomosciOperationCompleted);
            }
            this.InvokeAsync("PobierzWiadomosci", new object[] {
                        token,
                        timT}, this.PobierzWiadomosciOperationCompleted, userState);
        }
        
        private void OnPobierzWiadomosciOperationCompleted(object arg) {
            if ((this.PobierzWiadomosciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzWiadomosciCompleted(this, new PobierzWiadomosciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WyslijWiadomosc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komunikat WyslijWiadomosc(string token, Wiadomosc wiadomosc) {
            object[] results = this.Invoke("WyslijWiadomosc", new object[] {
                        token,
                        wiadomosc});
            return ((Komunikat)(results[0]));
        }
        
        /// <remarks/>
        public void WyslijWiadomoscAsync(string token, Wiadomosc wiadomosc) {
            this.WyslijWiadomoscAsync(token, wiadomosc, null);
        }
        
        /// <remarks/>
        public void WyslijWiadomoscAsync(string token, Wiadomosc wiadomosc, object userState) {
            if ((this.WyslijWiadomoscOperationCompleted == null)) {
                this.WyslijWiadomoscOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWyslijWiadomoscOperationCompleted);
            }
            this.InvokeAsync("WyslijWiadomosc", new object[] {
                        token,
                        wiadomosc}, this.WyslijWiadomoscOperationCompleted, userState);
        }
        
        private void OnWyslijWiadomoscOperationCompleted(object arg) {
            if ((this.WyslijWiadomoscCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WyslijWiadomoscCompleted(this, new WyslijWiadomoscCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Komunikat {
        
        private string trescKomunikatuField;
        
        private long kodKomunikatuField;
        
        /// <remarks/>
        public string trescKomunikatu {
            get {
                return this.trescKomunikatuField;
            }
            set {
                this.trescKomunikatuField = value;
            }
        }
        
        /// <remarks/>
        public long kodKomunikatu {
            get {
                return this.kodKomunikatuField;
            }
            set {
                this.kodKomunikatuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Wiadomosc {
        
        private string nazwaUzytkownikaField;
        
        private string trescWiadomosciField;
        
        private int stempelCzasowyField;
        
        private long numerPokojuField;
        
        /// <remarks/>
        public string nazwaUzytkownika {
            get {
                return this.nazwaUzytkownikaField;
            }
            set {
                this.nazwaUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public string trescWiadomosci {
            get {
                return this.trescWiadomosciField;
            }
            set {
                this.trescWiadomosciField = value;
            }
        }
        
        /// <remarks/>
        public int stempelCzasowy {
            get {
                return this.stempelCzasowyField;
            }
            set {
                this.stempelCzasowyField = value;
            }
        }
        
        /// <remarks/>
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                this.numerPokojuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Karta {
        
        private figuraKarty figuraField;
        
        private kolorKarty kolorField;
        
        /// <remarks/>
        public figuraKarty figura {
            get {
                return this.figuraField;
            }
            set {
                this.figuraField = value;
            }
        }
        
        /// <remarks/>
        public kolorKarty kolor {
            get {
                return this.kolorField;
            }
            set {
                this.kolorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum figuraKarty {
        
        /// <remarks/>
        K2,
        
        /// <remarks/>
        K3,
        
        /// <remarks/>
        K4,
        
        /// <remarks/>
        K5,
        
        /// <remarks/>
        K6,
        
        /// <remarks/>
        K7,
        
        /// <remarks/>
        K8,
        
        /// <remarks/>
        K9,
        
        /// <remarks/>
        K10,
        
        /// <remarks/>
        KJ,
        
        /// <remarks/>
        KD,
        
        /// <remarks/>
        KK,
        
        /// <remarks/>
        KA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum kolorKarty {
        
        /// <remarks/>
        pik,
        
        /// <remarks/>
        kier,
        
        /// <remarks/>
        karo,
        
        /// <remarks/>
        trefl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Uzytkownik {
        
        private long identyfikatorUzytkownikaField;
        
        private string nazwaUzytkownikaField;
        
        private long numerPokojuField;
        
        private Karta[] handField;
        
        private Karta[] najUkladField;
        
        private int kickerField;
        
        private bool foldField;
        
        private int wartField;
        
        private string nazwaUkladuField;
        
        private bool startField;
        
        /// <remarks/>
        public long identyfikatorUzytkownika {
            get {
                return this.identyfikatorUzytkownikaField;
            }
            set {
                this.identyfikatorUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public string nazwaUzytkownika {
            get {
                return this.nazwaUzytkownikaField;
            }
            set {
                this.nazwaUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                this.numerPokojuField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] hand {
            get {
                return this.handField;
            }
            set {
                this.handField = value;
            }
        }
        
        /// <remarks/>
        public Karta[] najUklad {
            get {
                return this.najUkladField;
            }
            set {
                this.najUkladField = value;
            }
        }
        
        /// <remarks/>
        public int kicker {
            get {
                return this.kickerField;
            }
            set {
                this.kickerField = value;
            }
        }
        
        /// <remarks/>
        public bool fold {
            get {
                return this.foldField;
            }
            set {
                this.foldField = value;
            }
        }
        
        /// <remarks/>
        public int wart {
            get {
                return this.wartField;
            }
            set {
                this.wartField = value;
            }
        }
        
        /// <remarks/>
        public string nazwaUkladu {
            get {
                return this.nazwaUkladuField;
            }
            set {
                this.nazwaUkladuField = value;
            }
        }
        
        /// <remarks/>
        public bool start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Key {
        
        private long identyfikatorUzytkownikaField;
        
        private string tokenField;
        
        /// <remarks/>
        public long identyfikatorUzytkownika {
            get {
                return this.identyfikatorUzytkownikaField;
            }
            set {
                this.identyfikatorUzytkownikaField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ZarejestrujCompletedEventHandler(object sender, ZarejestrujCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZarejestrujCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZarejestrujCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ZalogujCompletedEventHandler(object sender, ZalogujCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZalogujCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZalogujCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void WylogujCompletedEventHandler(object sender, WylogujCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WylogujCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WylogujCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ZmienHasloCompletedEventHandler(object sender, ZmienHasloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZmienHasloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZmienHasloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ResetujHasloCompletedEventHandler(object sender, ResetujHasloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetujHasloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetujHasloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UsunKontoCompletedEventHandler(object sender, UsunKontoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UsunKontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UsunKontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzTokenyCompletedEventHandler(object sender, PobierzTokenyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzTokenyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzTokenyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Key[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Key[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzUzytkownikowCompletedEventHandler(object sender, PobierzUzytkownikowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzUzytkownikowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzUzytkownikowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Uzytkownik[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Uzytkownik[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PobierzWiadomosciCompletedEventHandler(object sender, PobierzWiadomosciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzWiadomosciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzWiadomosciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Wiadomosc[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Wiadomosc[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void WyslijWiadomoscCompletedEventHandler(object sender, WyslijWiadomoscCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WyslijWiadomoscCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WyslijWiadomoscCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komunikat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komunikat)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591